# NUMPY 

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
# ndarray.ndim
# the number of axes (dimensions) of the array.
a.ndim

2

In [4]:
#  This is a tuple of integers indicating the size of the array in each dimension.
a.shape

(3, 5)

In [5]:
# the total number of elements of the array.
a.size

15

In [6]:
# an object describing the type of the elements in the array.
a.dtype

dtype('int32')

In [7]:
# the size in bytes of each element of the array. 
a.itemsize

4

In [8]:
# the buffer containing the actual elements of the array
a.data

In [9]:
type(a)

numpy.ndarray

In [10]:
x=np.array([[1,3],[3,4]],dtype=float)
x

array([[1., 3.],
       [3., 4.]])

In [11]:
x=np.array([[1,3],[3,4]],dtype=complex)
x

array([[1.+0.j, 3.+0.j],
       [3.+0.j, 4.+0.j]])

In [12]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.empty((2,4))

array([[4.67296746e-307, 1.69121096e-306, 1.29061142e-306,
        1.89146896e-307],
       [7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
        1.29061142e-306]])

In [15]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

# Basic Operations

In [16]:
a=np.array([2,3,4,5,7])
b=np.ones((1,5))
print(a-b)

[[1. 2. 3. 4. 6.]]


In [17]:
a*5

array([10, 15, 20, 25, 35])

In [18]:
a**2

array([ 4,  9, 16, 25, 49])

In [19]:
a>3

array([False, False,  True,  True,  True])

In [20]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

In [21]:
# elementwise product
A*B

array([[2, 0],
       [0, 4]])

In [22]:
# matric product
A@B

array([[5, 4],
       [3, 4]])

In [23]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [24]:
A.sum()

3

In [25]:
A.min()

0

In [26]:
A.max()

1

In [27]:
A.mean()

0.75

In [28]:
A.transpose()

array([[1, 0],
       [1, 1]])

In [64]:
def f(x,y):
    return x+y;
x=np.fromfunction(f,(3,3),dtype="int64")
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]], dtype=int64)

In [29]:
A.sort()
A

array([[1, 1],
       [0, 1]])

In [54]:
A.cumsum() # cumulative sum of elements

array([1, 2, 2, 3])

In [31]:
A.sum(axis=1)

array([2, 1])

In [55]:
a.cumprod() # cumulative product of elements

array([  2,   6,  24, 120, 840])

In [56]:
#np.compress(condition, a, axis=None, out=None)
np.compress(a>3,a)  #  a slice along that axis is returned in output for each index where condition evaluates to True

array([4, 5, 7])

In [57]:
# np.extract(condition, arr)
np.extract(a>2,a)  # compress is equivalent to extract.

array([3, 4, 5, 7])

# Universal Functions

In [32]:
s=np.arange(4)
s

array([0, 1, 2, 3])

In [33]:
np.exp(A)

array([[2.71828183, 2.71828183],
       [1.        , 2.71828183]])

In [35]:
np.log(B)

C:\Users\heman\AppData\Local\Temp\ipykernel_27544\4061543246.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(B)


array([[0.69314718,       -inf],
       [1.09861229, 1.38629436]])

In [37]:
np.sqrt(49)

7.0

# Statistics

In [38]:
A.mean()

0.75

In [39]:
A.std()  #standard deviation 

0.4330127018922193

In [40]:
A.var() #variance 

0.1875

In [44]:
np.cov(A)  #covariance

array([[0. , 0. ],
       [0. , 0.5]])

# Questions

In [47]:
A.all()

False

In [48]:
A.any()

True

In [49]:
A.nonzero()

(array([0, 0, 1], dtype=int64), array([0, 1, 1], dtype=int64))

In [51]:
np.where(a>3)

(array([2, 3, 4], dtype=int64),)

# Indexing, Slicing 

In [58]:
a[:3]

array([2, 3, 4])

In [59]:
a[::-1]

array([7, 5, 4, 3, 2])

In [60]:
w=np.array([[1,2,3],[5,6,7],[9,7,6]])
w[:,2] #all row and third col

array([3, 7, 6])

# Shape

In [67]:
w.shape

(3, 3)

In [69]:
 w.ravel()   # returns the array, flattened

array([1, 2, 3, 5, 6, 7, 9, 7, 6])

In [72]:
w.reshape(9,1)

array([[1],
       [2],
       [3],
       [5],
       [6],
       [7],
       [9],
       [7],
       [6]])

In [75]:
w.resize(1,9)
w

array([[1, 2, 3, 5, 6, 7, 9, 7, 6]])